### ISSUE TITLE
\titleformat no longer allows easy mode

### ISSUE THREAD

**Issue by nakerman** [jbezos/titlesec#11]
Since updating to the package version 2.11, `\titleformat` appears not to work in easy settings as before. The following line: 

`\titleformat*{\subsubsection}{\itshape}`

as presented in the documentation produces the following error message: 

`Package titlesec Error: Not allowed in `easy' settings`

which it did not previously.

Any idea if this has something to do with the update? I noticed in the changes file that you removed the .tss files, and the only other person with this issue was several years ago, who then resolved it by correctly installing the tss files.

Thanks!

**Comment by jbezos** [comment]
Please, provide a minimal example showing the problem. My tests work as expected.

**Comment by jbezos** [comment]
Maybe related?:

https://tex.stackexchange.com/questions/500970/titlesec-s-update-2-10-2-%e2%86%92-2-11-caused-subparagraphs-not-working-in-scrbookclas/501176#501176

**Comment by jbezos** [comment]
Not enough data.

**Comment by c-bg** [comment]
Hi! 
I have the same problem: 
Error: 
```! Package titlesec Error: Not allowed in `easy' settings.```

version: 
```
Package: titlesec 2019/10/16 v2.13 Sectioning titles
```

small example: 

```
\documentclass[fontsize=8pt,paper=a4,pagesize]{scrartcl}

\usepackage{titlesec}

\renewcommand{\thesubsection}{\textbf{\arabic{section}.\arabic{subsection}}}

\titleformat*{\section}{\normalfont\huge}
\titleformat*{\subsection}{\normalfont\Large}

\def\titleprefix{ }

\usepackage[a4paper,top=2.5cm, left=2.95cm, right=2.95cm]{geometry}

\usepackage{titlesec}

\begin{document}

\subsection*{\textbf{6.1} bla}

\end{document}
```
Please let me know if you need more information.

**Comment by jbezos** [comment]
See the link above: KOMA classes are not compatible with `titlesec` any more. Sorry.

**Comment by c-bg** [comment]
Ah okay, I did not realize that this is deliberate.
Thanks much for your prompt answer!
