### ISSUE TITLE
Partial TOCs not working since 2.11

### ISSUE THREAD

**Issue by fzieris** [jbezos/titlesec#12]
This might be related to the fix of #9.

I just upgraded this package from 2.10.2 to 2.11 and now my per-chapter TOCs are gone.

Creating a MWE proved difficult. Starting from the `\printcontents` example on page 17 in the documentation, I tried the following, which results in `LaTeX Error: Missing \begin{document}`:

```latex
% Does not compile
\documentclass{book}
\usepackage{titlesec,titletoc}

\titleformat{\chapter}{}{}{0pt}{}[\startcontents\printcontents{l}{1}[2]{}]
\titlecontents*{lsection}[0pt]{\small\itshape}{}{}{}[ \textbullet\ ][.]

\begin{document}
    \chapter{A}
    \section{B}
\end{document}
```

When I get rid of the `\titleformat`, pdflatex runs cleanly, but the PDF does not contain the local TOC:

```latex
% Produces no TOC using v2.11
\documentclass{book}
\usepackage{titlesec,titletoc}

\titlecontents*{lsection}[0pt]{\small\itshape}{}{}{}[ \textbullet\ ][.]

\begin{document}
    \chapter{A}
    \startcontents
    \printcontents{l}{1}[2]{}
    \section{B}
\end{document}
```

Using package version 2.10.2 (e.g. on OverLeaf, https://www.overleaf.com/read/twrnbwssrprp) with the `\setcounter` work-around the same code works just fine:

```latex
% Produces TOC using v2.10.2
\documentclass{book}
\usepackage{titlesec,titletoc}

\titlecontents*{lsection}[0pt]{\small\itshape}{}{}{}[ \textbullet\ ][.]

\begin{document}
    \chapter{A}
    \startcontents
    \printcontents{l}{1}{\setcounter{tocdepth}{2}}
    \section{B}
\end{document}
```

Am I doing something wrong (then the documentation needs a fix) or is this an actual bug?

**Comment by fzieris** [comment]
In case anyone has a similar issue, and struggles going back to an older package version: I downloaded the ZIP bundle from commit 8258c907cee2a35a31c6607430b93ee1f7693397 (there are tags in this repo, and that commit appears to be version 2.10.2, give or take) and replaced the package files manually. Needless to say that this is a dirty fix for my particular situation. I can only advise against upgrading to 2.11 until this issue is resolved.

**Comment by jbezos** [comment]
I'll take a look, but right now I'm somewhat busy. Therefore, expect a month or so for a fix and stick to the previous version.

**Comment by FrankMittelbach** [comment]
@jbezos basically it looks like partial tocs are dead in general after this upgrade (basically \ttlb@... comes out as -1000 and then the tocentry is not set). If you don't have time to look then I would advice to revert temporarily to an earlier version and push that until you have time to look at in in more detail.

**Comment by jbezos** [comment]
Does the version currently in GitHib work for you? The bug is supposed to be fixed (I'll release it in a few days, after some additional tests).

**Comment by FrankMittelbach** [comment]
I hadn't tried that, but yes, it looks like that it does -- thanks

**Comment by jbezos** [comment]
There were in fact two issues. (1) A mistake in the docs, because there was a missing pair of braces (to ‘hide’ `[2]`):

`\titleformat{\chapter}{}{}{0pt}{}[{\startcontents\printcontents{l}{1}[2]{}}]`

(2) The partial TOCs were broken. They are now fixed.
