### ISSUE TITLE
2.11 breaks titlesec usage on MiKTeX (missing .tss file)

### ISSUE THREAD

**Issue by kevinvalk** [jbezos/titlesec#13]
I was using the following titleformat together with MiKTeX (LuaLaTeX). With the recent update, the InputIfFileExists triggers an install of the titlesec package as it cannot find block.tss.

However, as this file is not provided anymore, MiKTeX just dies with a fatal error. As far as I can see, the checking if it is a default shape (symbol) should be done before trying to load a file.

```
\titleformat{\chapter} % command
	[block] % shape
	{\huge\bfseries} % format
	{\thechapter} % label
	{2ex} % sep
	{} % before-code
	[] % after-code
```

Thanks!

**Comment by jbezos** [comment]
The following works for me:
```
\documentclass{book}

\usepackage{titlesec}

\titleformat{\chapter} % command
	[block] % shape
	{\huge\bfseries} % format
	{\thechapter} % label
	{2ex} % sep
	{} % before-code
	[] % after-code
 
\begin{document}

\chapter{Title}

\end{document}
```
Checking is done in the meant order - if there is local file (perhaps modified), it takes priority over the default one. It looks as a problem with the MikTeX installer. Please, could you send the log?

**Comment by kevinvalk** [comment]
I originally thought it was a MikTeX issue and posted it there https://github.com/MiKTeX/miktex-packaging/issues/119

Let me know if you need more details, thanks!

**Comment by jbezos** [comment]
I'm closing it because the log shows it's an problem with MikTeX:
```
installing package titlesec triggered by tex/latex/titlesec\block.tss
````
I don't use MikTeX, so I'm sorry I cannot help, but `block.tss` is not a component of `titlesec` any longer and `\InputIfFileExists` must trigger nothing.
