### ISSUE TITLE
\part can't be assigned a \titleclass (low-level error)

### ISSUE THREAD

**Issue by FrankMittelbach** [jbezos/titlesec#17]
Trying to `\assignpagestyle{empty}` to a `\part` heading I first wanted to make it officially a top class (because without that `\assignpagestyle`has no effect (which I think is documented):
```
\documentclass{report}

\usepackage{titlesec}

\titleclass\part{top}

%\assignpagestyle\part{empty}

\begin{document}

\part{Test}

foo bar

\end{document}
```
But this dies with a rather nasty low-level error:
```
./Untitled.tex:11: Missing number, treated as zero.
<to be read again> 
                   }
l.11 \part{Test}
                
? 
```

**Comment by FrankMittelbach** [comment]
Any new on this issue Javier ?

**Comment by jbezos** [comment]
After reading the manual, I'm not sure (literally) this is valid setup. For new levels it's clear there must be a `\titleformat` and a `\titlespacing`, but for existing ones it says nothing. My logic says they must be redefined, but this point is not explicitly stated (only a couple of generic comments about the need to define the format).

**Comment by FrankMittelbach** [comment]
I stand corrected and I'm happy enough to explicitly document that this only works if \part is redefined using \titleformat, but somewhere it say it needs \titleformat or \titleclass:

> Notes. \titlespacing does not work with either \chapter and \part unless you change its title format as well by means of \titleformat, the simple settings, or \titleclass.

 it even gives the example of setting \titleclass{\part}{straight} which doesn't work without first using \titleformat (not checked if it does then).

But in any case I think it is bad if you can set this and then get a low-level counter error later

**Comment by jbezos** [comment]
Fixed, with a meaningful error, and submitted to CTAN
