### ISSUE TITLE
a fiew errors

### ISSUE THREAD

**Issue by BS67** [jbezos/titlesec#19]
Hello Jbezos, 
Since a few weeks, the titlesec parameters I did last year don't work. 
And I'm sure that is it the titlesec package which make those bugs because when I remove every lines linked to the titlesec package, it works. But without the titleformat 
Here is  a little file with every problems I met : 
[
[a fiew errors.zip](https://github.com/jbezos/titlesec/files/3617844/a.fiew.errors.zip)
](url)
Those errors are : 
-Format/spacing not found 
-I was unable to find the format corresponding to section.
Maybe you haven't set it with \titleformat and \titlespacing
-A number should have been here; I inserted `0'.
-Something's wrong--perhaps a missing \item. 
I hope you will answers quickly to my questions, because I need it very quickly
BS
PS : the modifying of the colour of the title should be added in the package

I you can't open the files, there is it : 
`\documentclass[12pt,twoside]{report}
\usepackage{titlesec}
\titleformat{\chapter}[hang]{\bf \huge}{\thechapter.}{2pc}{0}[1cm]
\begin{document}
\chapter{lorem1}
\section{lorem2}
ipsum
\end{document}`

**Comment by BS67** [comment]
`\documentclass[12pt,twoside]{report}

\usepackage{titlesec}
\titleformat{\chapter}[hang]{\bf \huge}{\thechapter.}{2pc}{0}[1cm]
\begin{document}
\chapter{lorem1}
\section{lorem2}
ipsum
\end{document}`

**Comment by jbezos** [comment]
Seems related to (but not the same as) https://github.com/jbezos/titlesec/issues/13 (two versions installed at the same time). Please, see the manual for the correct syntax of `\titleformat`.
