### ISSUE TITLE
titlesec not preserving raggedleft / flushright

### ISSUE THREAD

**Issue by scrouthtv** [jbezos/titlesec#21]
MWE:
```
  1 \documentclass{article}
  2 %\usepackage{titlesec}
  3 
  4 \begin{document}
  5 \raggedleft{}
  6 \section{Title}
  7 \end{document}
```
Which looks like:

![DeepinScreenshot_select-area_20190928210433](https://user-images.githubusercontent.com/23227405/65821436-bf2c3400-e235-11e9-9f42-e16cf53fef0d.png)

If I change the shape / format of \section to runin, the title *is* flush right, but I can't get it to print a line break after the title.
__Also I can't add the flushright command to titleformat because in my document I have some right flushed and some left flushed titles.__

**Comment by jbezos** [comment]
You must add the alignment to sections with `\usepackage[raggedleft]{titlesec}`.

If it changes, you must use `\titleformat` and define an intermediate macro, which you can redefine with `\renewcommand` to be either `\filright` or `\filleft`.
