### ISSUE TITLE
titleps and babel in TexLive 2019

### ISSUE THREAD

**Issue by fulminemizzega** [jbezos/titlesec#23]
Hello,
I encountered this same issue with TexLive 2019 (with italian setting)
https://tex.stackexchange.com/questions/511782/does-titleps-conflict-with-babel

**Comment by jbezos** [comment]
A change in the LaTeX kernel has broken `babel`, and this issue in turn affects `titleps`. I've committed a new version of `babel` apparently fixing it, but I must make some additional tests before uploading it to CTAN (very likely in a few days).

**Comment by jbezos** [comment]
An `titleps` relied on the fact `\markboth` was expandable, which is not the case with the latest LaTeX.
