### ISSUE TITLE
Chapter number in Roman numerals and \appendix

### ISSUE THREAD

**Issue by ivalb** [jbezos/titlesec#25]
Suppose we want the chapter number in Roman numerals and the appendices, as usual, numbered with letters. The following code produces an error, even if the output is correct. How can you avoid this problem? I know of other solutions (for examples with \renewcommand{\thechapter}{\Roman{chapter}}), but I'm looking for a solution involving _titletoc_.

### A minimal (not)working example

```
\documentclass{book}
\usepackage{titletoc}

\makeatletter
\def\mycontentslabel{\@Alph{\thecontentslabel}}

\titlecontents{chapter}
[1em]
{}
{\mycontentslabel\quad}
{}
{\contentspage}
\makeatother

\begin{document}

\tableofcontents

\chapter{Titolo}

  \appendix
    \chapter{Titolo prima appendice}
    \chapter{Titolo prima appendice}

\end{document}
```

**Comment by jbezos** [comment]
`\thecontentslabel` is not a number, but the lable (in this case ‘A’).

**Comment by ivalb** [comment]
I know that \ thecontentslabel is not a number but a letter in the chapters after \ appendix. 
This is precisely the problem.

Should I then deduce that, **using \ titlecontents**, it is impossible to define a style that produces chapters with Roman numerals and appendices numbered with letters?

Thank you!

**Comment by jbezos** [comment]
The label is generated by the sectioning command, so you should redefine the latter. For general questions related to how to use the package, please ask on sites like https://tex.stackexchange.com/ .
