### ISSUE TITLE
Wrong hyperlinks in table of contents

### ISSUE THREAD

**Issue by jbezos** [jbezos/titlesec#3]
From Berry Schoenmakers
Dear Javier,

I like using titlesec and titletoc very much. 

But I'm experiencing a nasty problem. I found out that, for instance, your manual file also has this problem, see

http://tug.ctan.org/macros/latex2e/contrib/titlesec/titlesec.pdf

This takes youto the version with date 2016-03-21.

PROBLEM: see page 1, the table of contents. For example, now look at the line:

    4. Additional Notes 10

If you click on the page number &quot;10&quot;, it will take you to page 3, at the start of &quot;3.1 Format&quot;.

This problems occurs always when using the starred versions of \titlecontents. 

I hope you see a way to resolve this. 

Kind regards,
  Berry Schoenmakers

**Comment by jbezos** [comment]
Hyperlinks are handled by `hyperref`, which redefines some `titlesec` macros. The problems seem to be in the line:

        \def\noexpand\Hy@tocdestname{#4}% 

The definition should be global:

       \gdef\noexpand\Hy@tocdestname{#4}%

**Comment by jbezos** [comment]
I've fixed it with a little hack in `titletoc`.

**Comment by donjuardo** [comment]
@jbezos I’m still experiencing this issue. Consider the following MWE.

```latex
\documentclass{article}
\usepackage{biblatex, titlesec, hyperref}

\addbibresource{bib.bib}

\begin{document}
\tableofcontents
\section{Section}
\nocite{Doe2023}
\newpage
\printbibliography[heading = bibintoc]
\end{document}

```

In the table of contents, the references entry is hyperlinked to the previous section (here just called “Section”). Tested with both pdfLaTeX and LuaLaTeX.
