### ISSUE TITLE
Problem with titlesec and  Tex Live 2019

### ISSUE THREAD

**Issue by MarcelSchaible** [jbezos/titlesec#30]
Hi,

I am using titlesec now since years and I am getting after an update of texlive the following strange error in the generated pdf (leading "0pt"):

0ptIntroduction

In our document we use the follwing definitions:

\usepackage{titlesec}
\titlespacing{\section}{0pt}{6pt}{6pt}
\titlespacing{\subsection}{0pt}{4pt}{4pt}
\titlespacing{\subsubsection}{0pt}{4pt}{4pt}
\titlespacing{\paragraph}{0pt}{4pt}{4pt}

Environment: pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian)

Our template can be found here: https://www.fernuni-hagen.de/kn/autsys/resources/ConfAutSys_template.zip

Any idea?

Thanks

Marcel

**Comment by jbezos** [comment]
The class is `scrbook`, which has removed its compatilbility with `titlesec`. See:

https://github.com/jbezos/titlesec/issues/22

Sorry I can't help.

**Comment by MarcelSchaible** [comment]
Ok, thanks for your help!
