### ISSUE TITLE
\label inside \section doesn't work with pagestyles

### ISSUE THREAD

**Issue by amunn** [jbezos/titlesec#34]
A `\label` command inside a sectioning command fails when a pagestyle is being used. If the `\label` is outside of the sectioning command it works, or if the pagestyle is not declared, it works.  I assume that `\label` is typically supposed to be inside the element being labelled. 

```
\documentclass{article}
\usepackage[pagestyles]{titlesec}

\newpagestyle{main}{%
\setfoot{}{}{}
}
\pagestyle{main}

\begin{document}

\section{Foo\label{foo}}

\section{Bar}

\end{document}
```

**Comment by amunn** [comment]
Adding `\protect` solves things, (ht barbara beeton) but this is not required with the standard classes.

**Comment by jbezos** [comment]
I’m closing this issue because there is a duplicate: https://github.com/jbezos/titlesec/issues/64.
