### ISSUE TITLE
TOC of subsections in a single section

### ISSUE THREAD

**Issue by schremmera** [jbezos/titlesec#38]
Right after each section title, I would like a TOC of the subsections in _that_ section and _that section only_--- just the way after each chapter title I have a TOC of the sections in that chapter. 

However, titletoc’s 

\startcontents[sections]
\printcontents[sections]{p-}{2}[2]

prints _all_ the subsections in the chapter and I have not been able to figure out what to do.

**Comment by jbezos** [comment]
Please, keep in mind the issue tracker is not intended as a general support forum, but for reporting bugs and feature requests. For other type of questions, consider asking at https://tex.stackexchange.com/ . I'm closing this issue because this is neither a bug nor a feature request.
