### ISSUE TITLE
adjust number of arguments of `\ttl@gobblecontents` to current LaTeX

### ISSUE THREAD

**Issue by u-fischer** [jbezos/titlesec#39]
Since more than a year LaTeX writes `\contentsline` with 4 arguments:

~~~~
\documentclass{article}

\begin{document}
\tableofcontents
\section{abc}

\end{document}
~~~~

gives 

~~~~
\contentsline {section}{\numberline {1}abc}{1}{}%
~~~~

So there is no longer a difference of the argument number with and without hyperref.
Could `titletoc` please changes its definition of `\ttl@gobblecontents` to 

~~~~
\def\ttl@gobblecontents#1#2#3#4{\ignorespaces}%
~~~~

Then hyperref could remove its redefinition.

**Comment by jbezos** [comment]
Fixed and submitted to CTAN.
