### ISSUE TITLE
titlespacing command does not seem to modify spacing after section title

### ISSUE THREAD

**Issue by amine-aboufirass** [jbezos/titlesec#40]
I'm trying to make my own custom section title spacing using the `titlespacing` command in the `titlesec` package. I devised the following MWE:

```
\documentclass[11pt, a4paper]{article}
\usepackage{titlesec}

\newcommand{\leftspacing}{0pt}
\newcommand{\beforespacing}{0pt}
\newcommand{\afterspacing}{0pt}
\titlespacing{\section}{\leftspacing}{\beforespacing}{\afterspacing}

\begin{document}
  \section*{First Section}
  \section*{Second Section}
  \section*{Third Section}
  \section*{Fourth Section}
\end{document}
```

It turns out that modifying `\leftspacing` and `\beforespacing` visibly modifies the spacing between the sections in the rendered PDF, but `\afterspacing` does not. How can I have full control over the spacing after my sections?

**Comment by jbezos** [comment]
Sorry for the late answer. I’ve made some test and it works as expected. Can you be more precise?

**Comment by jbezos** [comment]
I’m closing this issue because it seems to work aa expected and no additional clarification has been provided.
