### ISSUE TITLE
Footnotes missing from chapter/section with multiple footnotes

### ISSUE THREAD

**Issue by drinckes** [jbezos/titlesec#43]
If a chapter or section includes multiple footnotes within the title, only the last footnote will be shown at the bottom of the page.

Example:

```
\documentclass{report}
\usepackage{titlesec}
\titleformat*{\section}{\sffamily\Large\itshape}

\begin{document}
\section[The section]{The section{\footnote{First note.}\footnote{Second note.}}}
\end{document}
```
The section heading looks like:
> The section<sup>12</sup>

But the footnote section at the bottom of the page only includes:
> <sup>2</sup>Second note.

This only happens with titlesec, and for headings that have their titleformat redefined.

**Comment by jbezos** [comment]
Sorry for the late reply. I was completely sure the manual explained this limitation (namely, just one footnote per section), but I’ve found it is missing because at some point (between 2011 and 2015) I removed it by accident. Well, it’s a limitation and I’ll restore the note.

**Comment by jbezos** [comment]
Restored the note in development.
