### ISSUE TITLE
Creating new "tss" like things ?

### ISSUE THREAD

**Issue by mikamyara** [jbezos/titlesec#44]
Dear all,
  I used a previous version of titlesec and built the  chapframe.tss file below. It worked well with : 
```tex
\titleformat{\chapter}[chapframe]
            {\normalfont\structColor}
            {\Large\sffamily\chaptername~\thechapter~-}
            {0pt}
            {\Large\bfseries\sffamily}
            [{\startcontents[chapterToc]}]
```
With the new version of titlesec it does not work anymore. I saw the "tss" mechanism did not require to be used for now but was supported. I don't know where to find the problem. I tried the folliwing : in the sty file, I see the definition of the block tss, copy/paste it in my latex preamble and renamed it blockb. Then the titleformat call does not seem to understand.

Can you help ?

 Regards,
    Mike

```
\gdef\ttlh@chapframe#1#2#3#4#5#6#7#8{%
\gdef\ttl@makeline##1{\hspace{#6}##1\hspace{#7}}%
\setlength\leftskip{#6}%
\setlength\rightskip{#7}%
\interlinepenalty\@M
\ttl@beginlongest
\makeatletter
\def\thechapterimage{chapter-header-2.jpg}
\begin{tikzpicture}[remember picture,overlay]
\node at (current page.north west)
{\begin{tikzpicture}[remember picture,overlay]
\node[anchor=north west,inner sep=0pt] at (0,0) {\includegraphics[width=\paperwidth]{\thechapterimage}};
\draw[anchor=west] (\Gm@lmargin,-4cm) node [line width=2pt,rounded corners=15pt,draw=structColor,fill=white,fill opacity=0.5,inner sep=15pt]{\strut\makebox[22cm]{}};
\draw[anchor=west] (\Gm@lmargin+.3cm,-4cm) node {#2 #4{#8}};
\end{tikzpicture}};
\end{tikzpicture}
\makeatother
\par\vspace*{0\p@}
\ttl@endlongest}
```

**Comment by jbezos** [comment]
Sorry for the late reply. Please, could you post a minimal complete example?

**Comment by jbezos** [comment]
I’m closing this issue because no MWE has been provided.
