### ISSUE TITLE
Inserting document title in the header using the titleps package while combined with the titlesec package

### ISSUE THREAD

**Issue by md-al-imran-abir** [jbezos/titlesec#46]
[https://tex.stackexchange.com/q/626018/219947](https://tex.stackexchange.com/q/626018/219947)

When I use only the `titleps` package, the following code works and puts the document title in the header.

```
\documentclass{article}
\usepackage{titling}
\usepackage{geometry}
\usepackage{titleps} 
\usepackage{duckuments}

\title{A friendly duck}
\author{Duck}
\date{\today}

\newpagestyle{myFancy}[\normalsize\bfseries]{
    \setheadrule{0.4pt}%
    \sethead[\thetitle][][]%
            {\thetitle}{}{}%
}
\pagestyle{myFancy}

\begin{document}
    \maketitle
    \duckument
\end{document}
```

[![enter image description here][1]][1]

But when I combine the `titleps` package with the `titlesec` package using the command `\usepackage[pagestyles]{titlesec}`, the output is not as expected. It puts 'section no' in one header and 'subsection no' in another.

```
\documentclass{article}
\usepackage{titling}
\usepackage{geometry}
\usepackage[pagestyles]{titlesec} 
\usepackage{duckuments}

\title{A friendly duck}
\author{Duck}
\date{\today}

\newpagestyle{myFancy}[\normalsize\bfseries]{
    \setheadrule{0.4pt}%
    \sethead[\thetitle][][]%
            {\thetitle}{}{}%
}
\pagestyle{myFancy}

\begin{document}
    \maketitle
    \duckument
\end{document}
```

2nd page

[![enter image description here][2]][2]

3rd page

[![enter image description here][3]][3]

It can be solved by directly inserting the title in the `\newpagestyle` command like this:
```
\newpagestyle{myFancy}[\normalsize\bfseries]{
    \setheadrule{0.4pt}%
    \sethead[A friendly duck][][]%
            {A friendly duck}{}{}%
}
```

But it would be great to have a solution using something like `\thetitle` so that one doesn't need to change the title manually thrice instead of once.

  [1]: https://i.stack.imgur.com/zQ2vU.png
  [2]: https://i.stack.imgur.com/V6jx2.png
  [3]: https://i.stack.imgur.com/cBDbf.png

**Comment by jbezos** [comment]
Sadly, both `titlesec` and `titling` define `\thetitle` with different meanings. As `\thetitle` has been part of `titlesec` for about 25 years, there is very little I can do. They are just incompatible.
