### ISSUE TITLE
Color setting doesn't work when selecting [wrap] or [drop] through titleformat

### ISSUE THREAD

**Issue by HuangXiaoKai** [jbezos/titlesec#49]
# description
I tried to format my subsection title using 
```
\titleformat{name=\subsection}[hang]{\bfseries\color{red}}{}{-0.5cm}{}
```
title color changs to red normaly. Same to shapes [block] and [runin].
However, when choosing shapes [drop] and [wrap], color setting fails to show any effect while `\bfseries` still works.
This may be a bug to fix. 

# MWE
```
\documentclass{article}
\usepackage{titlesec} 
\usepackage{lipsum}
\usepackage{xcolor}

\titleformat{name=\subsection}[wrap]{\bfseries\color{red}}{}{-0.5cm}{}
\titlespacing*{name=\subsection}{5cm}{*10}{*5}

\begin{document}

\section{Introduction}
\subsection{Part}
\lipsum[2]
\end{document}
```
![image](https://user-images.githubusercontent.com/22166802/182995222-20433ec7-fb90-4dc2-a566-e1f00101253f.png)

This example is compiled by XeLaTeX in overleaf.

**Comment by jbezos** [comment]
Because of the way colors are handled, this bug is not easily fixable without the risk of backward incompatibility. I’ll document a workaround in the manual (wrap the text with `\textcolor`). I’ve marked this issue as ‘known issue’.
