### ISSUE TITLE
Missing \protected@file@percent

### ISSUE THREAD

**Issue by Rimole** [jbezos/titlesec#55]
titlesec 2021/07/05 v2.14 has 
\def\ttl@tocsep{\addvspace{10\p@}}
which should be
\def\ttl@tocsep{\addvspace{10\p@}\protected@file@percent}
because it is writing to the table of contents (see "\protected@file@percent" in source2e.pdf).
Thank you!

**Comment by jbezos** [comment]
Please, post a MWE showing a real issue. In principle, spaces in vertical mode are ignored, and the standard classes add nothing.

**Comment by jbezos** [comment]
Not an actual issue.
