### ISSUE TITLE
Issue with header when using table of contents and starred chapters

### ISSUE THREAD

**Issue by GL314159** [jbezos/titlesec#57]
When using a starred version of chapter, the header "Contents" instead of writing the correct chapter name in the header. Why is that the case? How to fix it? (See [https://tex.stackexchange.com/questions/675335/titlesec-issue-with-table-of-contents-and-starred-chapters](url)).

```
\documentclass{book}
\usepackage{titlesec}

\newpagestyle{main}{%
  \headrule
  \sethead{\chaptername\ \thechapter}{}{\chaptertitle}
  \setfoot{}{}{\thepage}
}

\begin{document}
\pagestyle{main}
\tableofcontents
\chapter*{intro}
b \newpage b
\chapter{test}
a \newpage b
\end{document}
```

**Comment by jbezos** [comment]
This is the default behavior in LaTeX. You need a combination of `\chaptermark` and `\ifthechapter`. See the `titleps` and the manual for further details. Note also the warning in the log file:
```
Package titlesec Warning: You are using an old interface for page styles
(titlesec)                (or you forgot the package option 'pagestyles').
(titlesec)                You could proceed but don't complain if you run
(titlesec)                into errors.
```
