### ISSUE TITLE
Using titlesec within new (from-scratch) class - no labels

### ISSUE THREAD

**Issue by ndrwstn** [jbezos/titlesec#59]
I am trying to use titlesec within a from-scratch class I am creating. I had thought it would be possible using the `loadonly` package option, but it is not working properly.

Specifically, while it creates the sectioning commands as expected, the label does not show up for anything other than first level sections (one created with `\titleclass{name}[level]{class}`).

No doubt this was not what this package was intended for, but it seems silly to develop my own sectioning system when titlesec works better than anything I could make.

I'd appreciate any help.

### MWE
```
\documentclass{minimal}
\usepackage[loadonly]{titlesec}

\newcounter{part}
\renewcommand{\thepart}{\Alph{part}}
\newcounter{section}[part]
\renewcommand{\thesection}{\arabic{section}}

\titleclass{\part}[0]{straight}
\titleformat{\part}[block]{\bfseries\filcenter}{\thepart{}.\  }{0pt}{}{}
\titlespacing{\part}{0pt}{3ex}{2ex}[0pt]

\titleclass{\section}{straight}[\part]
\titleformat{\section}[hang]{\bfseries}{\thesection{}.\ }{0pt}{}{}
\titlespacing{\section}{0pt}{2ex}{1ex}[0pt]


\begin{document}
\part{Main Part}
\section{This is the first topic.}
First topic text.
\section{This is the second topic.}
Second topic text.
\end{document}
```

### Output
[mwe-loadonly.pdf](https://github.com/jbezos/titlesec/files/11520269/mwe-loadonly.pdf)

**Comment by jbezos** [comment]
You forgot to set the `secnumdepth`. For example: `\setcounter{secnumdepth}{2}`.

**Comment by ndrwstn** [comment]
Ugh. My apologies, I'm an idiot for not realizing this was the problem. Thank you for the help.
