### ISSUE TITLE
missed dot line for reference and index

### ISSUE THREAD

**Issue by KSJhon** [jbezos/titlesec#60]
I am making a book with references and index section.
I used `\bibliography{bibliography}' and `\printindex'.
And I created toc as:
```tex
\clearpage\maketitle
\thispagestyle{empty}
\cleardoublepage
\frontmatter
%\setempty
\pagenumbering{Roman}
\tableofcontents*
%\thispagestyle{empty}
\thispagestyle{plain}
\clearpage
\listoffigures*
%\thispagestyle{empty}
\thispagestyle{plain}
\cleardoublepage

\mainmatter%
 ```

But I cannot find dot lines for references and index section.
Others are ok.
Please help me.

**Comment by jbezos** [comment]
There is no mention at all in your code of `titlesec`. If what you want is a ‘how to’, please ask in forums like https://tex.stackexchange.com/. If you consider there is a bug, post a minimal example showing the issue.
