### ISSUE TITLE
Uneven spacing in multiline titles involving diacritics

### ISSUE THREAD

**Issue by mmotejlek** [jbezos/titlesec#62]
In multiline titles, there's a larger gap between the first and second line than between subsequent lines if diacritics are present on the second line.

![illustration](https://github.com/jbezos/titlesec/assets/44536244/20eb07f0-8eb6-420f-a8a0-87bd8ebf85f2)

Without titlesec:
```latex
\documentclass{article}

\begin{document}
	\section{É \newline É \newline É \newline É}
\end{document}
```

With titlesec and **no** diacritics on the second line:
```latex
\documentclass{article}

\usepackage{titlesec}

\begin{document}
	% no diacritics on the second line
	\section{É \newline E \newline É \newline É}
\end{document}
```

With titlesec and diacritics on the second line:
```latex
\documentclass{article}

\usepackage{titlesec}

\begin{document}
	\section{É \newline É \newline É \newline É}
\end{document}
```

Issue appears when compiling with pdflatex, xelatex and lualatex.

Titlesec is from TeX Live 2023.

**Comment by jbezos** [comment]
`titlesec` inserts some struts to improve the spacing in typical cases, but in some others it can lead to undesired results. Just use the `nostruts` package option:
```tex
\usepackage[nostruts]{titlesec}
```

**Comment by mmotejlek** [comment]
Thank you for the solution! Although it is not ideal if there can be negative side-effects. I immediately ran into a bad iteraction with `microtype`'s protrusion.

For posterity, the issue with microtype was that the first line of a title was slightly outdented and was fixed by including \noprotrusion like this:

```
\titleformat{\section}{\nostruts}{\noprotrusion\thesection}{1em}{}
```
