### ISSUE TITLE
Captial Case TOC, with clickable entries

### ISSUE THREAD

**Issue by R-van-Bakel** [jbezos/titlesec#65]
I want to have a table of contents where some entries (sections and subsections) are all in uppercase. I managed to get it working with the following code:

`\titlecontents{section}[2pc]{\addvspace{6pt}\bfseries}{\contentslabel{2pc}\MakeUppercase}{}{\titlerule*[0.3pc]{.}\contentspage}[\addvspace{8pt}]`
(similar code is used for the subsections)

This does have the unfortunate side-effect that the entries in question are now not clickable anymore, i.e. they don't link to the respective pages. Is there a solution to this problem, or should I perhaps make the entries uppercase in another way?

**Comment by jbezos** [comment]
Please, keep in mind the issue tracker is not intended as a general support forum, but for reporting bugs and feature requests. For other type of questions, consider asking at https://tex.stackexchange.com/ . I'm closing this issue because this is neither a bug nor a feature request.
