### ISSUE TITLE
Broken titleps page style with clearpage and thispagestyle after a custom environment

### ISSUE THREAD

**Issue by vepain** [jbezos/titlesec#66]
I'm suspect a bug concerning `titleps`, custom environment and `\clearpage` command.

I asked the community in tex.stackexchange about this issue: https://tex.stackexchange.com/questions/695942/broken-titleps-page-style-with-clearpage-and-thispagestyle-after-a-custom-enviro 

(I can copy the question here if you prefer)

**Comment by jbezos** [comment]
I’m closing this issue because it was solved in tex.stackexchange.
