### ISSUE TITLE
How to use the same titleformat for numbered and unnumbered chapters/sections?

### ISSUE THREAD

**Issue by yuki** [jbezos/titlesec#67]
I'm using titlesec with **explicit** option, and I have a titleformat for chapters like this:

```latex
\RequirePackage[explicit]{titlesec}

\titleclass{\chapter}{straight}
\titleformat{name=\chapter}[block]
{\huge\bfseries} 
{\thechapter. #1 } 
{0pt}
{}    
\titlespacing{\chapter} {0pt}{0pt}{0pt} 
```

I need to put some "\chapter*{name}" in my document, and I have seen that they doesn't appear until I put the next code:

```latex
\titleformat{name=\chapter,numberless}[block]
{\huge\bfseries} 
{#1 } 
{0pt}
{}    
\titlespacing{\chapter} {0pt}{0pt}{0pt} 
```

Is there any way to not repeat the code (I know it's not 100% equal) and use one maybe the unnumbered to use for numbered chapter?

Thanks!

**Comment by jbezos** [comment]
Please, keep in mind the issue tracker is not intended as a general support forum, but for reporting bugs and feature requests. For other type of questions, consider asking at https://tex.stackexchange.com/ . I'm closing this issue because this is neither a bug nor a feature request.
