### ISSUE TITLE
titlesec incompatible with babel-latvian

### ISSUE THREAD

**Issue by eg9** [jbezos/titlesec#68]
Source: https://tex.stackexchange.com/q/696889/4427

As described in the answer, there are actually two culprits: `babel-latvian` uses
```
\ifx\chapter\undefined
```
which is not the best way to check for undefinedness; on the other hand, `titlesec` does
```
\expandafter\ifx\csname <csname>\endcsname\relax
```
in several places. As far as I can see, none of these requires expandability, so the test might be
```
\begingroup\expandafter\endgroup\expandafter\ifx\csname <csname>\endcsname\undefined
```
which wouldn't keep `\<csname` equivalent to `\relax`.

But nowadays
```
\ifcsname <csname>\endcsname
```
is a much safer test.

**Comment by jbezos** [comment]
`\expandafter\ifx\csname <csname>\endcsname\relax` is just the former definition of `\@ifundefined`. The very reason I used the ’expansion’ was the code was clearer to my eyes (no braces) and I didn’t expect a change in its behavior.
