### ISSUE TITLE
References using nameref disappeared after titlesec update

### ISSUE THREAD

**Issue by suricata78** [jbezos/titlesec#71]
With the latest update of the titlesec package (from v2.14 to v2.15) all references using nameref disappeared.

This MWE shows the issue:
```
\documentclass{article}

\usepackage{titlesec}
\usepackage{hyperref}

\begin{document}

\section{This is my section}
\label{label:thisisthelabel}

This is my reference: \nameref{label:thisisthelabel}

\end{document}
```
Note: This seems to be related to the following reported issue [@currentlabelname is not correctly sanitized](https://github.com/jbezos/titlesec/issues/64).

Please also see @u-fischer's answer to the issue on Stack Exchange: [https://tex.stackexchange.com/a/699596/215495](https://tex.stackexchange.com/a/699596/215495)

**Comment by jbezos** [comment]
Thanks. I’ll revert it in a few days and reopen the issue as ‘known issue’.
