### ISSUE TITLE
Need help with \titleformat

### ISSUE THREAD

**Issue by subidit** [jbezos/titlesec#72]
NOT AN ISSUE. JUST NEED HELP. 

What would be a simple way to define `\titleformat` to get output like - 
`\section{\hrulefill Introduction \hrulefill}`

I got to it in a couple of ways but all my solutions looks too complicated for the task. I have tried 

```LaTeX
% 1. runin
\titleformat{\section}[runin]{\Large\bfseries}{}{}{\hrulefill}[\hrulefill]

% 2. Explicit
\usepackage[explicit]{titlesec}

\titleformat{\section}
  {\normalfont\Large\bfseries}
  {}
  {0pt}
  {\hrulefill #1 \hrulefill}
```
I want to know if there is a simpler way to achieve this. 

(P.S. there are so many other commands in the package, it would have been much easier if there were a command like \thesection to grab the #1 inputs. Then I could have done just
`{\hrulefill #1 \hrulefill}`

Also there is \centring, \filcenter etc. Which doesn't work nicely with \hrulefill.)

**Comment by jbezos** [comment]
Please, keep in mind the issue tracker is not intended as a general support forum, but for reporting bugs and feature requests. For other type of questions, consider asking at https://tex.stackexchange.com/ . I'm closing this issue because this is neither a bug nor a feature request.

**Comment by subidit** [comment]
Got it. Will do that. Thanks for the reply.
