### ISSUE TITLE
The page number cannot be obtained according to the \thecontentspage command

### ISSUE THREAD

**Issue by texno3** [jbezos/titlesec#73]
I want to format the page numbers of different values in the table of contents separately, so I want to judge the page numbers according to the value of \thecontentspage, but in 
```
\titlecontents{section}{}{}{}{
  \int_compare:nNnTF{\thecontentspage}>{1}
  {some \thecontentspage}
  {other \thecontentspage}
}
```
An error will be reported, I can not get its value, would like to ask if there is a way to distinguish the current page number value, thanks.

**Comment by jbezos** [comment]
Please, post a minimal working example.

**Comment by texno3** [comment]
```
\documentclass{article}
\usepackage{titletoc}

\begin{document}

\titlecontents{section}{}{\contentslabel{2.3em}}{}{
  \titlerule*[1pc]{.}
  \ExplSyntaxOn
  \int_compare:nNnTF{\thecontentspage}>{1}%Could not get the correct page number value
  {some cmds \thecontentspage}
  {other cmds \thecontentspage}
  \ExplSyntaxOff
}

\tableofcontents
\section{Section1}
\setcounter{page}{10}
\section{Section2}

\end{document}
```

**Comment by jbezos** [comment]
Your definition is wrong in at least a couple of points: missing _left_ argument and misplaced commands for Expl Syntax. Please, ask for help in forums like https://tex.stackexchange.com/. To get the catcodes right, you may need to define an auxiliary macro.
