### ISSUE TITLE
PDF does not compile if this brace is closed

### ISSUE THREAD

**Issue by samurai-for-hire** [jbezos/titlesec#80]
![image](https://github.com/user-attachments/assets/5c3afa0b-f281-4a9b-946f-cf8602dfc1e6)

This throws a 'runaway argument' error on line 84 and an 'unclosed group' warning on line 79. Attempting to add the closing brace will cause Overleaf to become stuck compiling. Compiling was aborted after 10 minutes. It does not throw an additional error if the compiling process is stopped.

**Comment by jbezos** [comment]
Please, post actual code, not images. Anyway, the syntax is incorrect. See the manual or ask a LaTeX forum.
