### ISSUE TITLE
titletoc: setting tocdepth counter is not local to partial TOC as claimed

### ISSUE THREAD

**Issue by FrankMittelbach** [jbezos/titlesec#9]
The documentation of `titletoc` states that one can  set `tocdepth` in the *toc-code* argument of `\printcontents` to **locally** restrict the partial toc depth. That appears work if the partial toc comes after the main TOC but in fact the setting is global as counters are global.

That could of course be fixed by always explicitly setting the `tocdepth`, but I think it is more natural to actually making that *toc-code* argument save and restore the `tocdepth` value, i.e., make the statement in the documentation true.

MWE:
[titletoc-test.tex.zip](https://github.com/jbezos/titlesec/files/3365574/titletoc-test.tex.zip)

**Comment by jbezos** [comment]
But what if the counter is not `tocdepth`? An ad hoc restoring of `tocdepth` doesn't solve the general problem, namely, `\setcounter` is global (interestingly, `\setlength` is local, so no problem here). I must think about it.

**Comment by FrankMittelbach** [comment]
The point is that one has to set tocdepth to have a partial toc that is limited but then the value is wrong afterwards. So your interface requires to set the value and thus should restore it. You can still say that this is the only counter in this argument which is managed but there is no use case for "locally" setting other counters. So I think you are ok if you document it.

**Comment by jbezos** [comment]
I'm considering the following options:
1) Save and restore `tocdepth`. This is an ad hoc solution and what the manual says is still wrong (except for `tocdepth`).
2) Define a macro local to this context, say, \localsetcounter, which sets the counter locally (or saves and restores it).
3) Redefine `\setcounter` in this context, so that the counter is set locally (or saved and restored).
4) Extend somehow `\printcontents`.

**Comment by FrankMittelbach** [comment]
>     1. Save and restore `tocdepth`. This is an ad hoc solution and what the manual says is still wrong (except for `tocdepth`).

well I think then the manual would be right if it states that counters are global within this goup (as they are everywhere else) except for tocdepth which is explicitly restored if changed

>     2. Define a macro local to this context, say, `\localsetcounter`, which sets the counter locally (or saves and restores it).

I think that is not good. It would only be needed for setting tocdepth (what other counters should be resaonably set in this context by a user?) and then having a special command seems pointless
 
>     3. Redefine `\setcounter` in this context, so that the counter is set locally (or saved and restored).

just during definition time? might work but is more trouble than save and restore just because there is a theoretical possibility (for which I really don't see any use case) that a user wants to set another counter which is meant to be local t this code

>     4. Extend somehow `\printcontents`.

In some sense that would be another good option because the desired tocdepth is in fact a sensible argument to this and it might look nicer to say `{2}[3]{...}` instead of `{2}{\setcounter{tocdepth}...}`

**Comment by jbezos** [comment]
Options 4 makes sense for me, too. Simple and consistent.

**Comment by FrankMittelbach** [comment]
@jbezos  ok :-) looking forward to an update then

**Comment by jbezos** [comment]
Fixed in 2.11.
